### ISSUE TITLE
Pothos::Archive does not portably encode size_t

### ISSUE THREAD

**Issue by FiachAntaw** [pothosware/pothos#111]
The new Pothos::Archive system doesn't explicitly specify the length of size_t. This causes issues when networking across 32-bit and 64-bit platforms (e.g. between an AMD64 Windows PothosGui instance and an ARMv7 Linux PothosUtil proxy).

Notably, attempting to open a PothosGui instance that has a cached connection to an incompatible server will cause it to crash with the message **"Exception: invalid map<K, T> key"** due to the following sequence of events:

- Line 37 of [gui\HostExplorer\HostSelectionTable.cpp](https://github.com/pothosware/pothos-gui/blob/e4ece7b4876b6332f6872c5b026fd9ac26423dee/HostExplorer/HostSelectionTable.cpp#L37) attempts to call Pothos::System::HostInfo::get on the remote server
- Line 45 of [lib\System\HostInfo.cpp](https://github.com/pothosware/pothos/blob/644cd5d2e0eb43161ba1b31123b9e829b62b3f0a/lib/System/HostInfo.cpp#L45) attempts to deserialize the 4-byte `size_t processorCount` field of the HostInfo object received from the server as an 8-byte number, due to the different size of size_t on ARMv7 (32-bit) and AMD64 (64-bit).
 - The remainder of the serialized data is incorrectly parsed. Importantly, the 'tid' field follows the serialized object in the archive and is thus lost.
- Line 82 of [lib\Remote\RemoteProxy.cpp](https://github.com/pothosware/pothos/blob/644cd5d2e0eb43161ba1b31123b9e829b62b3f0a/lib/Remote/RemoteProxy.cpp#L82) attempts to access the 'tid' argument of the deserialized RPC response, causing an `std::out_of_range` exception to be emitted.
- The exception block surrounding Line 37 of [gui\HostExplorer\HostSelectionTable.cpp](https://github.com/pothosware/pothos-gui/blob/e4ece7b4876b6332f6872c5b026fd9ac26423dee/HostExplorer/HostSelectionTable.cpp#L31-L54) does not catch this exception, and it bubbles to the Qt library where it causes a hard crash.

I'm unsure how to solve this without making breaking changes to Pothos::Archive, as I don't know of a way to differentiate size_t from it's implementing integer type via template magic (it appears to be `typedef unsigned int size_t` on ARMv7 GCC). I'm currently working around this [by serializing all integers as 64-bit](https://github.com/FiachAntaw/pothos/commit/c1dd8315b6a0f5fc3cfc0f56a625e454889e93b2), but that's clearly not a good solution.

**Comment by guruofquality** [comment]
Yikes. So I was aware of this because I patched the old archive stuff with the boost portable archive from eos. In this rewrite, I [always serialize long types as 64-bits](https://github.com/pothosware/pothos/blob/master/include/Pothos/Archive/Numbers.hpp#L132) because they can vary in size. I also thought that I was safe here for size_t because long or long long was always used for size_t. In this case its int on arm! whoops... so thanks for catching that.

Theres no way to actually check that the api user is passing in a size_t or an actual number thats of the same typedef. Because at the end of the day you just want to match it up with the same type or struct running on another machine.

I can think of two fixes off the top of my head. Serialize all ints as 64-bits like you said, or record the number of bytes in the number as part of the serialization data for all int, long, and long long types. That way the destination always knows exactly how many bytes to read out. Using an extra byte to communicate the size of the number isnt too bad, but I might want to review the `std::vector<number>` implementation so we arent wasting a lot of overhead packing the size in bytes for every element. Just thinking out loud..
