### ISSUE TITLE
MessageGenerator size parameter name clash with builit in size function in muparserx

### ISSUE THREAD

**Issue by ashley-b** [pothosware/pothos#123]
I don't see any errors in PothosGui, but from PothosUtils if i try to set the size of the MessageGenerator I get this error
`2017-05-19 14:56:34 Application: system exception`
I tack the throw site to muparserx ParserXBase::CheckForEntityExistence.  muparserx Readme.txt say 'size' is for matrix dimensions.
Also unrelated, MessageGenerator::setSize takes a const reference to size arg, I assume by value might be better.

**Comment by guruofquality** [comment]
I fixed the uncaught exception since it was from muparserx, theres now a better print if something like that happens again. Also the gui topology exporter has some simplification tweaks to avoid tuning the parameters into local variables in the evaluator when they dont have to be.

* https://github.com/pothosware/pothos/commit/f72f88c482de7379aaa3f07bc9fc00264febc752
* https://github.com/pothosware/pothos-gui/commit/4ab721cb15a00e9fab989f193cfc24ee59a184bc
