### ISSUE TITLE
Can't resize Widgets in OS X / QSizeGrip

### ISSUE THREAD

**Issue by mcbernie** [pothosware/pothos#33]
Dear Dev-Team,
on latest pothos (from git, build on El Capitan 10.11, qt5.5.0) the QSizeGrip in GraphWidgetContainer is not shown.

Here are my Solution:
**GraphWidgetContainer.cpp**
```
21a22,24
>         #ifdef __APPLE__
>         this->setFixedSize(10,10);
>         #endif //__APPLE__
```

>the QSizeGrip has been disabled in newer releases to keep parity with OS X, as size grips don't appear in Cocoa anymore. - http://stackoverflow.com/questions/18741210/size-grip-is-gone-from-status-bar-in-qt-5-1-on-macosx

**Comment by guruofquality** [comment]
The fix is pushed: https://github.com/pothosware/pothos/commit/26e66c6cfa32bc83d8f8a82f1065b1b86d08fff1 Occasionally, the look and feel defaults from platform to platform can cause an issue like this. Let us know if you catch anything else that seems to be rendered wrong or out of place. Thanks for the tip!
